---
volsync:
  network: dione
  provider: upcloud
  buckets:
    volsync:
      restic: true
    longhorn: {}

pds:
  network: dione
  provider: upcloud
  tailscale: true
  instance:
    enabled: true
  buckets:
    storage:
      provider: cloudflare
    backup:
      provider: cloudflare

authentik:
  network: dione
  provider: upcloud
  tailscale: true
  instance:
    enabled: true
    plan: CLOUDNATIVE-2xCPU-4GB
  buckets:
    storage:
      provider: cloudflare
    backup:
      provider: cloudflare
