---
volsync:
  network: dione
  provider: upcloud
  buckets:
    volsync:
      restic: true
    postgres:
      restic: true

pds:
  network: dione
  provider: upcloud
  buckets:
    blobs:

vault:
  network: dione
  provider: upcloud
  tailscale: true
  instance:
    enabled: true
    plan: 1xCPU-2GB
  buckets:
    storage: {}
    backup: {}
