---
volsync:
  network: dione
  provider: upcloud
  buckets:
    volsync:
      restic: true
    postgres:
      restic: true

tsrecorder:
  network: dione
  provider: upcloud
  buckets:
    data:

pds:
  network: dione
  provider: upcloud
  buckets:
    blobs:
