---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${MARIADB_NAME:-${APP}-mariadb}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "${MARIADB_NAME:-${APP}-mariadb}"
    template:
      data:
        password: "{{ .password }}"
        rootPassword: "{{ .rootPassword }}"
  dataFrom:
    - extract:
        key: db-${MARIADB_NAME:-${APP}-mariadb}
