---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "tsrecorder"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: "tsrecorder-secret"
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_access_key }}"
  dataFrom:
    - extract:
        key: ucos/haydenmoe-tsrecorder-data
