---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atproto-pds
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: atproto-pds-secret
    template:
      data:
        PDS_JWT_SECRET: "{{ .jwtSecret }}"
        PDS_ADMIN_PASSWORD: "{{ .adminPassword }}"
        PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: "{{ .rotationKeyK256PrivateKeyHex }}"
        PDS_EMAIL_SMTP_URL: "{{ .emailSmtpUrl }}"
        PDS_BLOBSTORE_S3_BUCKET: "{{ .bucket_name }}"
        PDS_BLOBSTORE_S3_REGION: europe-1
        PDS_BLOBSTORE_S3_ENDPOINT: "{{ .endpoint }}"
        PDS_BLOBSTORE_S3_ACCESS_KEY_ID: "{{ .access_key_id }}"
        PDS_BLOBSTORE_S3_SECRET_ACCESS_KEY: "{{ .secret_access_key }}"
        PDS_BLOBSTORE_S3_FORCE_PATH_STYLE: "false"
  dataFrom:
    - extract:
        key: app/atproto-pds
    - extract:
        key: ucos/haydenmoe-pds-blobs
