---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atproto-pds
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: atproto-pds-secret
    template:
      data:
        PDS_JWT_SECRET: "{{ .jwtSecret }}"
        PDS_ADMIN_PASSWORD: "{{ .adminPassword }}"
        PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: "{{ .rotationKeyK256PrivateKeyHex }}"
        PDS_EMAIL_SMTP_URL: "{{ .emailSmtpUrl }}"
  dataFrom:
    - extract:
        key: app/atproto-pds
