[env]
_.python.venv = { path = "{{ config_root }}/.venv", create = true }
KUBECONFIG = "{{ config_root }}/talos/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{ config_root }}/.minijinja.toml"
SOPS_AGE_KEY_FILE = "{{ config_root }}/age.key"
TALOSCONFIG = "{{ config_root }}/talos/talosconfig"
JUST_UNSTABLE = "1"
VAULT_ADDR="https://vault.hayden.moe"

# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
KUBERNETES_VERSION="v1.34.1"

# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
TALOS_VERSION="v1.11.1"

[settings]
python.uv_venv_auto = true

[tools]
"aqua:budimanjojo/talhelper" = "3.0.39"
"aqua:cilium/cilium-cli" = "0.18.8"
"aqua:FiloSottile/age" = "1.2.1"
"aqua:fluxcd/flux2" = "2.7.3"
"aqua:getsops/sops" = "3.11.0"
"aqua:helm/helm" = "4.0.0"
"aqua:helmfile/helmfile" = "1.2.2"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.33.1"
"cargo:minijinja-cli" = "latest"
terraform = "1.13.5"
talosctl = "1.11.5"
upctl = "3.21.0"
uv = "0.9.8"
gum = "0.17.0"
yq = "4.48.1"
just = "1.43.0"
"pipx:flux-local" = "7.11.0"
openbao = "2.4.3"
