[env]
_.python.venv = { path = "{{ config_root }}/.venv", create = true }
KUBECONFIG = "{{ config_root }}/talos/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{ config_root }}/.minijinja.toml"
SOPS_AGE_KEY_FILE = "{{ config_root }}/age.key"
TALOSCONFIG = "{{ config_root }}/talos/talosconfig"
JUST_UNSTABLE = "1"

# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
KUBE_VERSION="1.34.1"

# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
TALOS_VERSION="1.11.5"

[settings]
experimental = true
python.uv_venv_auto = true

[tools]
"aqua:FiloSottile/age" = "1.2.1"
"aqua:budimanjojo/talhelper" = "3.1.4"
"aqua:cilium/cilium-cli" = "0.18.9"
"aqua:fluxcd/flux2" = "2.7.5"
"aqua:getsops/sops" = "3.11.0"
"aqua:helm/helm" = "3.19.2"
"aqua:helmfile/helmfile" = "1.2.2"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.33.1"
"cargo:minijinja-cli" = "latest"
"pipx:flux-local" = "8.0.1"
gum = "0.17.0"
just = "1.43.1"
talosctl = "1.11.5"
terraform = "1.14.1"
upctl = "3.21.0"
uv = "0.9.16"
yq = "4.49.2"
