[project]
site_name = "Phoebe"
site_url = "https://hbjydev.github.io/phoebe"
site_description = "A Kubernetes homelab built on open source."
site_author = "hbjydev"
copyright = "&copy; 2025 Hayden Young"
repo_url = "https://github.com/hbjydev/phoebe"
repo_name = "hbjydev/phoebe"
edit_uri = "edit/main/docs/"

[project.theme]
font.text = "Geist"
font.code = "Geist Mono"
language = "en"
icon.repo = "fontawesome/brands/github"

features = [
  "content.action.edit",
  "content.action.view",
  "navigation.indexes",
  "navigation.path",
  "navigation.sections",
  "navigation.tabs",
  "navigation.tabs.sticky",
  "navigation.tracking",
  "search.highlight",
]

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
primary = "pink"
accent = "purple"

[[project.theme.palette]] 
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "pink"
accent = "purple"

[project.markdown_extensions.tables]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
pygments_lang_class = true

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]

[project.markdown_extensions.attr_list]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
