---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./atproto-pds/ks.yaml
  - ./beammp/ks.yaml
  - ./booklore/ks.yaml
  - ./bookshelf/ks.yaml
  - ./home-assistant/ks.yaml
  - ./immich/ks.yaml
  - ./plex/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./keycloak/ks.yaml
  - ./lidarr/ks.yaml
  - ./mediamanager/ks.yaml
  - ./paperless/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./qui/ks.yaml
  - ./radarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./starr-pg/ks.yaml
