---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: beammp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: beammp-secret
    template:
      data:
        BEAMMP_AUTH_KEY: '{{ .authKey }}'
  dataFrom:
    - extract:
        key: app-beammp
