---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${PG_NAME:-${APP}-pg}-barman"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "${PG_NAME:-${APP}-pg}-barman"
    template:
      data:
        ACCESS_KEY_ID: "{{ .accessKeyId }}"
        SECRET_ACCESS_KEY: "{{ .secretAccessKey }}"
  dataFrom:
    - extract:
        key: strg-ucos-haydenmoe-volsync-postgres
