---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz
spec:
  interval: 1h
  chart:
    spec:
      chart: signoz
      version: 0.111.0
      sourceRef:
        kind: HelmRepository
        name: signoz
      interval: 5m
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: signoz
    global:
      storageClass: ceph-block
      clusterName: &clusterName phoebe

    clusterName: *clusterName

    clickhouse:
      installCustomStorageClass: true
