---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: hayden-moe-tls-crt
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: hayden-moe-tls
  template:
    engineVersion: v2
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: tls-hayden.moe
          property: crt

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: hayden-moe-tls-key
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: hayden-moe-tls
  template:
    engineVersion: v2
    data:
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: tls-hayden.moe
          property: key

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pds-hayden-moe-tls-crt
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: pds-hayden-moe-tls
  template:
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: tls-pds.hayden.moe
          property: *key

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pds-hayden-moe-tls-key
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: pds-hayden-moe-tls
  template:
    data:
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: tls-pds.hayden.moe
          property: *key
