---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: victoria-metrics
spec:
  retentionPeriod: "7d"

  storageDataPath: /data
  volumes:
    - name: vm-data
      persistentVolumeClaim:
        claimName: victoria-metrics-metrics
  volumeMounts:
    - name: vm-data
      mountPath: /data

  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: 1000m
