---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepasswordSDK:
      vault: cluster-phoebe
      auth:
        serviceAccountSecretRef:
          name: 1password-sat
          namespace: external-secrets
          key: token
      integrationInfo:
        name: external-secrets-operator
        version: v1
