---
apiVersion: v1
kind: Secret
metadata:
  name: 1password-sat
spec:
  stringData:
    token: ENC[AES256_GCM,data:qzU1pl0Cx6WD/bJBqSzptbw2ZM2W66xqRMbPjbo8/P8DPH8i7sxv0Bkk3FmvZ4ylFzqvpleAG53wKuFPntS87UuRoaHr8vhr7jLOUkQmkc09E2UT5ZetHTn5SlldzEP7nFnERsbE4v/FXExFvj7CWOIIfHShKrvrfo3wagq9VclKB4MVtxrq1zBcLstBTP5lQafbZBqEJgb6BGVjh29Rn9o9UTiCjkCfHzL4zfyYmqZodUmGSOxEvP64oxwr2VkXioDdUue74dqFN0kH8qrIHEbXh1+ZMw1ikwvHY6MEJEm3EbuhP5cjNtwGcftDQSxYovpR5EXRIZzEg6DH5L0RdblVpBDJkqYl00WaWAU6XrqQFXUg91q72L0suXdKSF3Cd7iEc3pPRSk8Arvh6Es0lxbilmJaoto2t5vQiF0/bmNjQOQ00/zjXtHSFrmc8tzsLC0//gVrIw4bfMiM4PdkD+rC75H2k/GFsZdKfFy4Wesc5MsskF5/bL3AWg/kAEaOf3lg0YHTfMNaV7fwUGz5j5k/Dt6Shp6gizWECCxGagVSU2kzhH7peK4AXTasm9Gc0VocmROZCaGRGX/XcAyoZu5EH/dnmqchvn+jjI+pK+GobjTIALd7cIEOg2ijzUEtwqxttnWBodYHmjNZ0VaaduKtcx2vXy5lNkYmczImfVv1rDgiK5hq+xQHJbp88vBqw2vMBazokcLdNqH7bomcCrqExz7mP7i8mkPGR2Q92N/Vvx7T6310Wp8WPIWHA6HwuqH38U/5b+gjpWgvgKZnD2SjeljQQA1HVkrrYYirtMFci8LnYWavflVokDST2pKlnIUFfYdMkpyIwpQvtOESCD9kUUdqwHftpj3D9A62CXr6QqatXk1DZfBJuIavpldFOZE45YVgSWHxQhshj/NwoH6mp/T7vhmqS1mPjXq+cpU61ww0NilZ4j+Y7ir5cAHMRgOg6OrY3aICibRxVPo0C1uLdh3roWhogIrHC+/iNAF+fEOXF2mMf8l5tDu14RgDDqjtO6voHFJkP2v9gXUGfNfA+hLYoxX/W3HdcNcF2C8/OjbO/s4tVKueb0ayTzIzTCnY9swVd78hjhJObyzZ9p2d5Q0uQ1XAx8JJzMnqy+OiZ8RG,iv:MLguuAeWAoTslcxRZe+aBcdytW+KbRJViAjblGUX09o=,tag:i+TFzF4JnbYc/BIU1zOSkA==,type:str]
sops:
  age:
    - recipient: age16c45zxayen5nnfzd020wqz75wrca5mhkgdk95d5pwaazwzqed5asc8z4xw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dDcraFYyT2tGZlFFS0Jo
        Rk50RjI3RVBQT3RnS1hXYUxVVWV6bTJWVDNzCjAvbTU4cHErT0wvbXA3eWJTY2R6
        M3BBOVNYK2x2YUFnWHR0NEhveXNEd3cKLS0tIGFZTHVsRWgyNkNsUXNIUDZQWWUw
        N3FLelp1M04zOFJrZFJtbUJReXg1cDAKXTVI2inS+YxxF5lJxpZIE2KbaBNZYutR
        daMTpQ1qxKvOFUPYr7aI7CccRSC8GkEuLMduYJD2VY1Kyuj0qkyaCA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-20T00:53:08Z"
  mac: ENC[AES256_GCM,data:2Ud7GkjJXGAd9RBiLgTUGwm1mQDm74xrkqM33RyXuOdZstV9mZy4+AcEGjyDRaKkIHiZb+WSpIWJix9Jap2/4g5dZZpc9dwFqxJ1AclJsmbUJN0BwuuCQHnwFa3eMwDzhb1lFZoVIkQH5Z5EnsnUKYJcOf0VNbiQRrMPLBbk0Ig=,iv:oxs09mnl8o0JF3BRkohDrHJNkPk8Bh900XiwM4fOVVo=,tag:Mrp8k0/2htrK/FLup8SZuQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
