apiVersion: v1
kind: Secret
metadata:
  name: 1password-sat
stringData:
  token: ENC[AES256_GCM,data:Z3KFNaXMrU0swR+eHkxauL9Toh7auLHh2d1w7FqeFRsXcXotsPhLSEnZXySRDkR/cjiHHTGNo1gvDeMW+5f+VMnpsQgzhliicWXqUdrP+S99bsp+gVTwAGBJ26lfGiHWaeqx2SRUhWkRzaxmoD6Et2Z2CkvwHgVGBBcP9e1Vp/Gc7f1blMt3FbaWjYifXki7p8vDngY6kNKmUFyUJFRRu4uNRZyU5mWFw7TAHKVZVof6wLqgbzCuOW8+ThtZIcCpu9pCmZjcd2iB8zvZVSN2mtjYUDVEJkzMkD5t5E5TGHuaB97sdK9iz3zCT5T4p434NJFUmLR143lsfIWygoPAFmOOKBcooHf/lkEmdDonSOZyFqmF1ZbVXNmPdDfSmla0mZf+9BLHGumTOf3x5YTwEH+cVMGCFCdONc7ytaoX5lTy+BjoDsnZRCU0kEruHGoqB1rlnqhnLv2gxkyXeJzPhp/B306LaWwb4kMvVweKCcXaxOlJL51RR7yiRfedv5A23mH4HH886wxkazl06Dd6rGBs9fnT6C/5ThYSvBrNwvJwrSw6yuWlIkHCERfIhMw/sk/3nFB49A1PjJV1MJTyV4rIqq0sz9nBZZMcNFWvIb31aoImsby04le8/Tquwat16Em6Yjk9EDrhBYskHF/OXUQuj8GxuJqYTqh3Mp0Y7QZl+/szw2qz2QnmAKVrXqlBGXB8Zdj4gkxRFt+m97fB9U4lvbIzsQMDeT/GF2Ix4NE2uduC/rwK/5RtT2yD++SQikUpGGep54dRmJ1s8is38CaUwkDnzD4EkC5MHDiUyUD2ja73AS464V3F0VnJJBEK6qhnM88o4DbmLFKV5+W5+qrvGIh+e9bw3264xXr90XtjxuLChEaCc1R/6i1BwYl2Nsve9vSYr4S03UVpkun7xEd57JJbSrCo3FrUt5qA0GTdGZ8MIhco2S8He2rjE2CUe+fVn3I1AOPn+MWuM5ZbBOPDJsYteA7ReOTR3vI46vPWnu100PdWms1p3qo4qYntsVf+Ljf7QhRIYzxT6QHGvT+YKyqyrYRVPP//TPLn9zJqqS/XWdUiGLVr1Tv6dQiF8/tEEoUDcOD/71jb+qoYOfPW+dhfR+DD2rhjyc/MZO9qbfJU,iv:PA0hfDpL1dOpNfUhgA0wynwYMq7vBc07mDT61OfL2vg=,tag:J8NDs6itDFYC1ecM2p9rsg==,type:str]
sops:
  age:
    - recipient: age16c45zxayen5nnfzd020wqz75wrca5mhkgdk95d5pwaazwzqed5asc8z4xw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dDcraFYyT2tGZlFFS0Jo
        Rk50RjI3RVBQT3RnS1hXYUxVVWV6bTJWVDNzCjAvbTU4cHErT0wvbXA3eWJTY2R6
        M3BBOVNYK2x2YUFnWHR0NEhveXNEd3cKLS0tIGFZTHVsRWgyNkNsUXNIUDZQWWUw
        N3FLelp1M04zOFJrZFJtbUJReXg1cDAKXTVI2inS+YxxF5lJxpZIE2KbaBNZYutR
        daMTpQ1qxKvOFUPYr7aI7CccRSC8GkEuLMduYJD2VY1Kyuj0qkyaCA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-20T01:01:32Z"
  mac: ENC[AES256_GCM,data:0K9ZliSa2KaA5QCZIFJIipk9JRTskXBVNA0B3Hp5Qv6pyigUZHEPULEUFWZdRFxBUDj5KTKnTOpSitkXwJsgdH8FTjOeuzgIEijVrO5ADS8IGHRYcdsHb9eSS8dC6OjvRCjX/RQTc2w11SBVnpGxWXEuuURSE6nwStV9JCy9mRs=,iv:ehC903f6Q/uToB8PdVeAdNXjBqMW0GtZDsiS09vRULM=,tag:gKzW43MsiWslr9g9OBZTzQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
