apiVersion: v1
kind: Secret
metadata:
  name: 1password-sat
stringData:
  token: ENC[AES256_GCM,data:4aV/ZNgLdsi8Tvwm/E/5/xObm0DdvEKCov6cNaEgeZIyhqdkC5YGQ3nN3NUWjMCgddixTmSEOSFt62tQ9JFgbg2m93vR1qwKyMM5mxBHAl2/waXZVyB4xs3LKTFbuJZ6duDuWn0li6BanJkSweYiDGEQ+G+t+9nPWVhiIXknOERjtDWkcx9SrbV8O/HZFZzK6EiPxcNl/B2BJufVhumS1eWHSYyB+XghlO9i3Cmu9Ej2a1qjNWDcBxJJ6tck80/3wAXR7If+neCVOxGCFrBasBkj6GSETCNtFU7i+Js1cBCjeS92KU/F/+gLOs98yBDWYaluhcWpAXQEIY+DIT14JDtzBHqxxJb4uU/aFZXdeVNW3hDjvtRSBKk54DeIhk0VJP3A2N9ngLs/4HBmEzf8dA+AfVjwoMyFE3+A2YJjABN8pbg86zbVDtLNGSZQyXpTUqHkPUBcgxNVxFGWX0zml5D6T8ZrJqDb+DV+WI8DIHHh439YJTZtsZzz3lCZ0atWK5tGRMxuEDXM4CGh3vtjgiCakKXRYNRsCEAmp/AifDlrerJJmBAH0K8aXSXfQTAed7arhkU+FX8ChCfBISmPjMusyKoBZ1xSZzJkK95KwIqGzrcma6e8fklzmebsf96M/AursDHjVOd8lykoVFNWb6ItVTx8d1y89bEDJ/bhP83Mb63nvtODshFiEsjsspDrpNNCP5IKKR5TjJ02kVMnELxnxCdI70iFOEVAG1hr9n5M3QEH4iN3UPAZBi2ygxGyeLIs8eowkNskHQDbn+skT1S5aKkscEbTXx7N0YZVG7ccF+74bZYRCGcZVOItuy8ab/ekl7ZA+ID5EEsrrVZn6SNptx0AECr0T9dQdIIteCMlsCs02qISdqKc+c2yTUlnVgtB9qQ3ypkwtdOi/KLnC8oTCjHVJGNsqzleFGkrikIMvTNnlOujyDUmO7k+q975AM0SkWWmYQPa4VDz66Oc5t1EykJQ9sLcv5/6OMrdldko4MN44SHqxKHFu3YlRqSlcXEMNetmpZL3fnlYjDFo21aN2YSkkvIOJi3zysusVHhdcZlCjYi4nJ6Xp01PNVa1Nfmwb7+4ys3DBh8yEYuvaZmDVb9d4pr7N+C6BFcz9RNf4BYI,iv:gNgk061plBA8LSqpAGcdrIvKzuSjg5i/3ZOQ7KcQ0H4=,tag:Cn7e3fC/31UlQ+Jino3How==,type:str]
sops:
  age:
    - recipient: age16c45zxayen5nnfzd020wqz75wrca5mhkgdk95d5pwaazwzqed5asc8z4xw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dDcraFYyT2tGZlFFS0Jo
        Rk50RjI3RVBQT3RnS1hXYUxVVWV6bTJWVDNzCjAvbTU4cHErT0wvbXA3eWJTY2R6
        M3BBOVNYK2x2YUFnWHR0NEhveXNEd3cKLS0tIGFZTHVsRWgyNkNsUXNIUDZQWWUw
        N3FLelp1M04zOFJrZFJtbUJReXg1cDAKXTVI2inS+YxxF5lJxpZIE2KbaBNZYutR
        daMTpQ1qxKvOFUPYr7aI7CccRSC8GkEuLMduYJD2VY1Kyuj0qkyaCA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-20T12:14:18Z"
  mac: ENC[AES256_GCM,data:s4P0+CuSUYXrTdE9xKv/OwbkEx3QBx5tqNDCgBMUmJIqvKLWYeOjVjEHyKlfylCSTOW5RLQ6tYj0Tln/jlK9esTD+xMVCUe/dKvDmbc79HAnTIDYT4QfPT5PJgwm5v1oplk3PTjAEiTkfeqFWL8jmUmKeNoWd6ih21T7NOfOtj4=,iv:Ty8KvNAht+FbjlDGI3zTGnwmGEuyuAcbegxXBY6cS7U=,tag:/nWi5LB6nJGZBnMlH7BvJw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
