apiVersion: v1
kind: Secret
metadata:
  name: 1password-sat
stringData:
  token: ENC[AES256_GCM,data:6rJdxZ/C6v0Vo6CMnG0hr1lkHTRszkZbGmaBDJ8s8nnXIaUa85CHXRlNfDVfIPGDKlkpZaPL//PlnNv4dnkTtsdcTJgQ+DfSc0ZnX1T1IopWJ/fbn5t71xdbqlybH0UmIvBgNCvmc7cMu5kzN2z/f7DJrbGEVNLjRLxa7FzZ8AutVs3wuh8ysrp0IV2w0bKRKn5ppLH2t+UvlaQexyZpOoDpOUtH/4Eajpgf2rU0vdWyIhKjzg9apQGWLdeJV+5ReRvblK9m3yob6bJkvcU+Iwp/bgKkZ9BxnQbcGJ9EDX8c9UPXL8fRGcqXJzqOWcSNXubLWvQvX/f1KDnUGtx7sBxuN77I623QA+OD1yCcyvqVSGnvXFX5aNTXhXZ2niqZqVDaGNjWrNJIPwSe3i2bXLcEFu2GjLfpROmy082HrUWB5hgOMxeQZJ+0Yh/nXTmGVfH3TgoEg1a++ojx9dSJiXkADr7/QJvF5ZG0UAMtdum3oDIJrrsj76XzefErgw+iI7rilgEJW0Iwg4mHg84quwdcr2rnKjLuWgEi3uQ+GrNgR8hme/hET9OPl1uf0vVd24t3ROhR0xmxxil62ajmzT9uoFvXMLs6fBi71J00vFkiKqpUzcVvQSZ41EDWfc0tFy8DoySnFJtgsr+JLWxP8GQXpG8DLSSHfiiJhdFJNdqGLXNtrkUdAhL6GG26IPuck4Tytie4oLxv7bDovOAxwGgHmMgN54vaGOqWQzpZInXdYZrgc1a5OmXwUY2L2knMZ420gut7S3p/X7NsnELtyuuuXekmMQA5PWMz83DiABSRarKcnJK4/UzHH0IFZz/+3BJypeWvRAJfGwov69sUgJTqves2Y5zPbAuD3Vu6+vCLIQEE1Qwzdpvq+EKrKjRYWK48AJZSRgxjnTKyR/qhwHY18Se/hm8SeaawOjZw4u56EVhynF0HGE+SZUGGIYA46vPE/T9+j99KT9wwBmpgXa0ElpUeMGKPnI0g+jd1WVHMcHGcq/mUfC58Ix0dmzxbbhZaL7IjzOh3KQc8U2Sr+6jYhHDMjIm4rVkvBt4ts5q+BPLgg1adPI5ZZscOsf0TeKz0h6Mf4iiLVa/Qv67cT3qMDyXv8mas9pLpJwCdBJfZS/RT,iv:o7OIT3n64mNUI3qDzy9CIDUjq0wBa51e86faQlYAX/0=,tag:Y0u33nBZ6ocWU3zPw2qHYA==,type:str]
sops:
  age:
    - recipient: age16c45zxayen5nnfzd020wqz75wrca5mhkgdk95d5pwaazwzqed5asc8z4xw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dDcraFYyT2tGZlFFS0Jo
        Rk50RjI3RVBQT3RnS1hXYUxVVWV6bTJWVDNzCjAvbTU4cHErT0wvbXA3eWJTY2R6
        M3BBOVNYK2x2YUFnWHR0NEhveXNEd3cKLS0tIGFZTHVsRWgyNkNsUXNIUDZQWWUw
        N3FLelp1M04zOFJrZFJtbUJReXg1cDAKXTVI2inS+YxxF5lJxpZIE2KbaBNZYutR
        daMTpQ1qxKvOFUPYr7aI7CccRSC8GkEuLMduYJD2VY1Kyuj0qkyaCA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-20T12:12:16Z"
  mac: ENC[AES256_GCM,data:smw9wMDzqkuSBqA+TibDI68zxrpuLDD6p2opTjMMlGUT39hMxgDmlk9MGJqrb72fjmihK+eLvqfZ+LV++MajvwS9BzFoFTT5/ah5F6V5zqTIa6CpYmQUKooabIGa6+wNCWPMRA7P1YgcEyV0xxshkiUtshRdYCVFfGDxaMIYnmc=,iv:6ghNDJGXjvFsdpCtnlBtYCh1hcEX+Wy0jPHTDY6jqOQ=,tag:cmNP/Lcwr0ux1JnZOSXHew==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
