---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: piper
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: piper-secret
    template:
      data:
        SPOTIFY_CLIENT_SECRET: "{{ .spotifyClientSecret }}"
        SPOTIFY_CLIENT_ID: "{{ .spotifyClientId }}"

        LASTFM_API_KEY: "{{ .lastfmApiKey }}"

        ATPROTO_CLIENT_SECRET_KEY: "{{ .clientSecret }}"
        ATPROTO_CLIENT_SECRET_KEY_ID: "{{ .clientSecretId }}"
  dataFrom:
    - extract:
        key: app-piper
